// angular/helloworld/src/app/app.component.ts
import { Component } from '@angular/core';
import * as iquotes from 'iquotes';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'helloworld';
  quotes = [];

  constructor() {
    this.quotes = iquotes.all();
  }
}

<div *ngFor="let quote of quotes; let i = index">
  {{ i }} - {{ quote.quote }}
</div>

// react/helloworld/src/App.js
import React, { Component } from 'react';
import './App.css';
const iquotes = require('iquotes');

class App extends Component {
  render() {

  const quotes = iquotes.all();

  const quoteItems = quotes.map((quote, i) =>
    <div className="quote" key={i}>
      { i } - { quote.quote }
    </div>
  );

    return (
      <div>
        { quoteItems }
      </div>
    );
  }
}

export default App;
